version: '3'
services:
  selenium-fb:
    image: selenium/standalone-chromium:latest
    ports:
      - 4445:4444
      - 7901:7900
    restart: always
    shm_size: 2gb
    privileged: true
    environment:
      - OTEL_SDK_DISABLED=true

  selenium-kj:
    image: selenium/standalone-chromium:latest
    ports:
      - 4446:4444
      - 7902:7900
    restart: always
    shm_size: 2gb
    privileged: true
    environment:
      - OTEL_SDK_DISABLED=true

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    env_file:
      - .env
    restart: always
    depends_on:
      - selenium-fb
      - selenium-kj

