version: '3'
services:
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
    restart: always
    shm_size: 2gb

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:80
    env_file:
      - .env
    restart: always
    depends_on:
      - chrome

