version: '3'
services:
  selenium:
    image: selenium/standalone-chromium:latest
    ports:
      - 4444:4444
      - 7900:7900
    restart: always
    shm_size: 2gb
    privileged: true

  # # Only for local since we use mac
  #   platform: linux/x86_64

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:80
    env_file:
      - .env
    restart: always
    depends_on:
      - selenium

